apiVersion: v1
kind: Namespace
metadata:
  name: registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - image: registry:2
        imagePullPolicy: IfNotPresent
        name: registry
        ports:
        - containerPort: 5000
          name: registry
        env:
          - name: REGISTRY_AUTH
            value: htpasswd
          - name: REGISTRY_AUTH_HTPASSWD_REALM
            value: "Registry Realm"
          - name: REGISTRY_AUTH_HTPASSWD_PATH
            value: /auth/htpasswd
        resources:
          limits:
            cpu: 1000m
            memory: 2500Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
          - mountPath: /var/lib/registry
            name: registry-data
          - mountPath: /auth
            name: registry-auth
      volumes:
      - name: registry-data
        emptyDir: {}
      - name: registry-auth
        secret:
          secretName: registry-auth
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: registry
spec:
  ports:
    - port: 5000
      targetPort: registry
      protocol: TCP
  selector:
    app: registry
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-auth
  namespace: registry
type: Opaque
data:
  # testuser:digitaloceanloadbalancerissue
  htpasswd: dGVzdHVzZXI6JDJ5JDA1JEZhQnlkNEhiTEVod3QzSHBoZGVzVE9TQTJIemY3Vi43OUVoZDkudlFXdWoxNTM3by96dE9XCgo=
